/*
DROP TABLE ITEM_PROFISSIONAL CASCADE CONSTRAINTS;
DROP TABLE ATENDIMENTO_ITEM CASCADE CONSTRAINTS;
DROP TABLE ATENDIMENTO CASCADE CONSTRAINTS;
DROP TABLE SERVICO CASCADE CONSTRAINTS;
DROP TABLE PROFISSIONAL_FUNCAO CASCADE CONSTRAINTS;
DROP TABLE PROFISSIONAL CASCADE CONSTRAINTS;
DROP TABLE FUNCAO CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
*/

CREATE TABLE CLIENTE (
    ID_CLI INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    TELEFONE VARCHAR2(20) NOT NULL, -- contato 
    EMAIL VARCHAR2(100) UNIQUE, -- contato - é único para não ter problema de duplicação
    CPF VARCHAR2(14) UNIQUE, -- necessário para a nota fiscal
    -- trilha de auditoria completa (entidade)
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    ATUALIZADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETADO_EM TIMESTAMP NULL
);

CREATE TABLE FUNCAO (
    ID_FUNC INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    -- trilha de auditoria 
    -- hard delete já que não quebra histórico de vendas
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PROFISSIONAL (
    ID_PROF INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    TELEFONE VARCHAR2(20), -- contato
    -- trilha de auditoria completa (entidade)
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ATUALIZADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETADO_EM TIMESTAMP NULL
);

CREATE TABLE PROFISSIONAL_FUNCAO (
    ID_PROF INTEGER NOT NULL,
    ID_FUNC INTEGER NOT NULL,
    CONSTRAINT PK_PROF_FUNC PRIMARY KEY (ID_PROF, ID_FUNC),
    /* 
    FKs
    todo profissional tem pelo menos uma função (precisa de triggers)
    toda função pode ter pelo menos um profissional (já comporta) 
    */
    CONSTRAINT FK_PF_PROF FOREIGN KEY (ID_PROF) 
        REFERENCES PROFISSIONAL(ID_PROF) ON DELETE CASCADE,
    CONSTRAINT FK_PF_FUNC FOREIGN KEY (ID_FUNC) 
        REFERENCES FUNCAO(ID_FUNC) ON DELETE CASCADE
    -- trilha de auditoria não é necessária 
    -- (ligação pura - hard delete)
);

CREATE TABLE SERVICO (
    ID_SERV INTEGER NOT NULL PRIMARY KEY,
    ID_FUNC INTEGER NOT NULL, 
    NOME VARCHAR2(100) NOT NULL,
    PRECO_BASE NUMBER(10, 2) NOT NULL, -- R$xxx.xx
    DURACAO_MINUTOS INTEGER NOT NULL,
    -- FK - todo serviço só pode ser feito por uma função
    CONSTRAINT FK_SERV_FUNC FOREIGN KEY (ID_FUNC) 
        REFERENCES FUNCAO(ID_FUNC),
    -- trilha de auditoria completa (entidade)
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ATUALIZADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETADO_EM TIMESTAMP NULL
);

CREATE TABLE ATENDIMENTO (
    ID_ATEND INTEGER NOT NULL PRIMARY KEY,
    ID_CLI INTEGER NOT NULL,
    DATA_HORA_INICIO TIMESTAMP NOT NULL, 
    -- usaremos servico.duracao_minutos para organizar o final na agenda
    STATUS VARCHAR2(12) DEFAULT 'AGENDADO' NOT NULL, 
    -- estado do atendimento que só pode ser um dos abaixo
    CONSTRAINT CHK_ATEND_STATUS CHECK 
        (STATUS IN ('AGENDADO', 'EM_ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
    -- FK - todo atendimento tem apenas um cliente 
    CONSTRAINT FK_ATEND_CLI FOREIGN KEY (ID_CLI) 
        REFERENCES CLIENTE(ID_CLI),
     -- trilha de auditoria completa (entidade)
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ATUALIZADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETADO_EM TIMESTAMP NULL
);

CREATE TABLE ATENDIMENTO_ITEM (
    ID_ITEM INTEGER NOT NULL PRIMARY KEY,
    ID_ATEND INTEGER NOT NULL,
    ID_SERV INTEGER NOT NULL,
    VALOR_COBRADO NUMBER(10, 2) NOT NULL, 
    /* 
    existe para conseguir manter o valor real do atendimento
    mesmo que servico.preco_base mude 
    ------------------------------------------
    FKs
    todo atendimento tem pelo menos um item (precisa de stored procedures)
    todo item está em um atendimento (já comporta) 
    */
    CONSTRAINT FK_ITEM_ATEND FOREIGN KEY (ID_ATEND) 
        REFERENCES ATENDIMENTO(ID_ATEND) ON DELETE CASCADE,
    CONSTRAINT FK_ITEM_SERV FOREIGN KEY (ID_SERV) 
        REFERENCES SERVICO(ID_SERV),
    -- trilha de auditoria completa (entidade)
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ATUALIZADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETADO_EM TIMESTAMP NULL
);

CREATE TABLE ITEM_PROFISSIONAL (
    ID_ITEM INTEGER NOT NULL,
    ID_PROF INTEGER NOT NULL,
    CONSTRAINT PK_ITEM_PROF PRIMARY KEY (ID_ITEM, ID_PROF),
    /*
    FKs
    todo profissional apto (cofirme servico.id_func) 
        faz pelo menos um serviço (precisa de stored procedures)
    todo serviço é feito por pelo menos um profissional apto 
        (precisa de stored procedures)
    */
    CONSTRAINT FK_IP_ITEM FOREIGN KEY (ID_ITEM) 
        REFERENCES ATENDIMENTO_ITEM(ID_ITEM) ON DELETE CASCADE,
    CONSTRAINT FK_IP_PROF FOREIGN KEY (ID_PROF) 
        REFERENCES PROFISSIONAL(ID_PROF)
);
