CREATE TABLE CLIENTE (
    ID_CLI INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100)
);

CREATE TABLE FUNCAO (
    ID_FUNC INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100)
);

CREATE TABLE PROFISSIONAL (
    ID_PROF INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL
);

CREATE TABLE PROFISSIONAL_FUNCAO (
    ID_PROF INTEGER NOT NULL,
    ID_FUNC INTEGER NOT NULL,
    CONSTRAINT ID_PROF_FUNC PRIMARY KEY (ID_PROF, ID_FUNC),
    CONSTRAINT FK_PROF FOREIGN KEY (ID_PROF) 
        REFERENCES PROFISSIONAL(ID_PROF) ON DELETE CASCADE,
    CONSTRAINT FK_FUNC FOREIGN KEY (ID_FUNC) 
        REFERENCES FUNCAO(ID_FUNC) ON DELETE CASCADE
);

CREATE TABLE SERVICO (
    ID_SERV INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL
);

CREATE TABLE ATENDIMENTO (
    ID_ATEND INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100),
    ID_PROF INTEGER NOT NULL,
    ID_SERV INTEGER NOT NULL,
    ID_CLI INTEGER NOT NULL,
    CONSTRAINT FK_ATEND_PROF FOREIGN KEY (ID_PROF) 
        REFERENCES PROFISSIONAL(ID_PROF) ON DELETE CASCADE,
    CONSTRAINT FK_ATEND_FUNC FOREIGN KEY (ID_SERV) 
        REFERENCES SERVICO(ID_SERV) ON DELETE CASCADE,
    CONSTRAINT FK_CLI FOREIGN KEY (ID_CLI) 
        REFERENCES CLIENTE(ID_CLI) ON DELETE CASCADE
);